EEMS3D/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from explorer.views import DatasetViewset
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

router.register('datasets', DatasetViewset)


urlpatterns = [
    url(r'^', include(router.urls)),
    #url(r'^', DatasetViewset.as_view(), name='dataset-list'),
    url(r'^admin/', admin.site.urls),
    url(r'^explore/', include('explorer.urls')),
    url(r'^focalsites/', include('explorer.focalurls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

explorer/urls.py
from django.conf.urls import url, include
from explorer.views import DatasetUploadFormView, GetTileView, GetEEMSProgramView, ExplorerView, DataInfoView

urlpatterns = [
    url(r'^(?P<dataset>\d+)/', include([
        url('^$', ExplorerView.as_view(), name='explore'),
        url(r'eems-program/', GetEEMSProgramView.as_view(), name='eems-program'),
        url(r'(?P<layer>[\w\-/]+?)/', include([
            url(r'dimensions/$', DataInfoView.as_view(), name='data-info'),
            url(r'tiles/(?P<x>\d+)/(?P<y>\d+)$', GetTileView.as_view(), name='tiles'),
        ])),
    ])),
    url(r'^upload/$', DatasetUploadFormView.as_view(), name='dataset_upload'),
]

explorer/models.py
from django.db import models
from django.db.models.signals import post_delete
import uuid
import logging

# Create your models here.

logger = logging.getLogger(__name__)


class Dataset(models.Model):
    """ A netCDF4 file """
    name = models.CharField(max_length=140)
    uuid = models.CharField(max_length=36, default=uuid.uuid4)
    data_file = models.FileField(upload_to='uploads/attributes/', max_length=256)
    has_elev_file = models.BooleanField(default=True)
    elev_file = models.FileField(upload_to='uploads/elevation/', max_length=256)
    eems_program = models.FileField(upload_to='uploads/programs/', max_length=256)


def delete_file(sender, instance, **kwargs):
    if instance.file.name:
        try:
            instance.data_file.delete(save=False)
            if instance.has_elev_file:
                instance.elev_file.delete(save=False)
            instance.eems_program.delete(save=False)
        except IOError:
            logger.exception("Error deleting Dataset: %s" % instance.name)
            return


post_delete.connect(delete_file, sender=Dataset)


class Variable(models.Model):
    """ A Variable from a Dataset """
    name = models.CharField(max_length=256)
    long_name = models.CharField(max_length=256)
    dataset = models.ForeignKey(Dataset)
    x_dimension = models.IntegerField()
    y_dimension = models.IntegerField()

explorer/forms.py
from django.forms import ModelForm
from explorer.models import Dataset


class DatasetForm(ModelForm):
    class Meta:
        model = Dataset
        fields = ('name', 'data_file', 'eems_program', 'elev_file',)
        help_texts = {
            'elev_file': 'The file that contains the "elevation" ',
            'eems_program': 'The EEMS program for the data',
        }

explorer/views.py
import numpy as np
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from netCDF4 import Dataset as nc
from explorer.forms import DatasetForm
from explorer.models import Dataset, Variable
from explorer.parsers import EEMS3DParser
from explorer.serializers import DatasetListSerializer

from rest_framework import viewsets
from rest_framework import generics
from rest_framework.response import Response
EEMS_TILE_SIZE = (500,500)


class DatasetViewset(viewsets.ReadOnlyModelViewSet):
    queryset = Dataset.objects.all()
    serializer_class = DatasetListSerializer


class ExplorerView(View):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class DataInfoView(View):

    def get(self, request, *args, **kwargs):
        layer = str(kwargs['layer'])
        dataset = Dataset.objects.get(pk=kwargs['dataset'])
        response = dict()
        variables = Variable.objects.filter(dataset=dataset)
        found = False
        for variable in variables:
            if variable.name == layer:
                layer = variable.name
                found = True
                break

        if not found:
            return JsonResponse({layer: 'False'})

        if layer == 'elev' and dataset.has_elev_file:
            path = dataset.elev_file.path
        else:
            path = dataset.data_file.path

        with nc(path, 'r') as ds:

            var = ds.variables[layer][:]

            minimum = float(var.min())
            maximum = float(var.max())
            x = var.shape[1]
            y = var.shape[0]
            fill_value = str(ds.variables[layer]._FillValue)
            response[layer] = {'min': minimum, 'max': maximum, 'x':float(x), 'y':float(y), 'fill_value' : fill_value}

        return JsonResponse(response)


class GetTileView(View):

    def get(self, request, *args, **kwargs):
        y_start = int(kwargs['y'])
        y_end = y_start + EEMS_TILE_SIZE[0]
        x_start = int(kwargs['x'])
        x_end = x_start + EEMS_TILE_SIZE[1]
        layer = kwargs['layer']
        dataset = Dataset.objects.get(pk=kwargs['dataset'])
        response = dict()

        variables = Variable.objects.filter(dataset=dataset)

        found = False
        for variable in variables:
            if variable.name == layer:
                layer = variable.name
                found = True
                break

        if not found:
            return JsonResponse({layer : 'False'})

        if layer == 'elev' and dataset.has_elev_file:
            path = dataset.elev_file.path
        else:
            path = dataset.data_file.path

        with nc(path, 'r') as ds:
            var = ds.variables[layer][:]

            if x_start > var.shape[1] or y_start > var.shape[0]:
                return JsonResponse({layer: 'False'})

            x_end = var.shape[1] if x_end > var.shape[1] else x_end
            y_end = var.shape[0] if y_end > var.shape[0] else y_end
            response['fill_value'] = str(ds.variables[layer]._FillValue)
            if isinstance(var, np.ma.core.MaskedArray):
                sub_matrix = var.data[y_start:y_end, x_start:x_end]
                response[layer] = sub_matrix.ravel().tolist()
                response['x'] = sub_matrix.shape[1]
                response['y'] = sub_matrix.shape[0]
            else:
                sub_matrix = var[y_start:y_end, x_start:x_end]
                response[layer] = sub_matrix.ravel().tolist()
                response['x'] = sub_matrix.shape[1]
                response['y'] = sub_matrix.shape[0]

        return JsonResponse(response)


class GetEEMSProgramView(View):

    def get(self, request, *args, **kwargs):
        """ Returns an EEMS program parsed into a json object """
        dataset = Dataset.objects.get(pk=kwargs['dataset'])
        path = dataset.eems_program.path
        response = EEMS3DParser(path).get_model()
        return JsonResponse(response)


class DatasetUploadFormView(View):
    form_class = DatasetForm
    template_name = 'upload.html'
    #success_url = reverse_lazy('explore')   # TODO - fix this redirect on file uploads

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request, *args, **kwargs):
        dataset = self.form_class(request.POST, request.FILES)
        if dataset.is_valid():
            ds = dataset.save()

            # add attribute variables to dataset
            attr_data = nc(ds.data_file.path, 'r')
            variables = list(attr_data.variables.keys())
            for var in variables:
                shape = attr_data.variables[var].shape
                if len(shape) < 2:
                    shape = [shape[0], shape[0]]
                variable = Variable(name=var,
                                    long_name=attr_data.variables[var].long_name,
                                    dataset=ds,
                                    x_dimension=shape[0],
                                    y_dimension=shape[1]
                                    )
                variable.save()
            attr_data.close()

            # add elevation to dataset
            elev_data = nc(ds.elev_file.path, 'r')
            elev_shape = elev_data.variables['elev'].shape
            elev_variable = Variable(name='elev', dataset=ds, x_dimension=elev_shape[0], y_dimension=elev_shape[1])
            elev_variable.save()
            elev_data.close()
            return redirect('/explore/' + str(ds.id) + '/')
        else:
            return render(request, self.template_name, {'form': self.form_class()})

templates/explore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>I am a robot</title>
</head>
<body>

</body>
</html>

templates/focalviews.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sagebrush Focal Points</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
      <link href="{% static "css/base.css" %}" rel="stylesheet">
    <style>
        body { margin: 0; z-index: 1; }
        #scene { position:fixed; padding:0; margin:0; top:0; left:0; width: 100%; height: 100%; z-index: 0; }
        canvas {height: 100%; width: 100%;}
        #legend {position: fixed; top: 60px; right: 15px; z-index: 1}
        .legend-element {display: table-row; padding-left:10px;}
        .legend-image {display: table-cell;  width:34px; height:20px; border: 1px solid #c3c3c3;}
        .legend-label {display: table-cell; width:80px; height:23.5px; vertical-align: top; padding-left: 10px;}
        #explorer {position: fixed; z-index: 1; top: 60px; left: 15px;}
        table {border-collapse: separate!important;}
    </style>
  </head>
  <body>
    <script>
        var focal_sites = {{ focal_points | safe }};
    </script>

    {% include 'modals/focalviews_about.html' %}


      <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a href="#" class="navbar-brand">Sagebrush Focal Points</a>
              </div>
              <ul class="nav navbar-nav">
                    <li><a href="#" data-toggle="modal" data-target="#myModal">How-To</a></li>

                </ul>
          </div>
      </nav>

      <script src="{% static "js/dat.gui.min.js" %}"></script>
      <script src="{% static "js/three.min.js" %}"></script>
      <script src="{% static "js/OrbitControls.js"%}"></script>
      <script src="{% static "js/sprites.js" %}"></script>

    <div id="explorer" class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"></h3>
        <button type="button" class="panel-title" data-toggle="collapse" data-target="#providers-container" aria-hidden="false">Climate Providers</button>
      </div>
      <div id="providers-container" class="panel-body collapse">
        <div id="providers-zoomable">
          <div id="providers-tree"></div>
        </div>
      </div>
    </div>


    <div id="sidebar">
        <div id="console">
            <ul id="results"></ul>
        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <div id="scene"></div>
      <script src="{% static "js/bootstrap-waitingfor.min.js" %}"></script>
      <script src="{% static "js/focalpoints.js" %}"></script>
  </body>
</html>

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EEMS 3D - Prototype</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <style>
        body { margin: 0; z-index: 1; }
        #scene { position:fixed; padding:0; margin:0; top:0; left:0; width: 100%; height: 100%; z-index: 0; }
        canvas {height: 100%; width: 100%;}
        #legend {position: fixed; top: 60px; right: 15px; z-index: 1}
        .legend-element {display: table-row; padding-left:10px;}
        .legend-image {display: table-cell;  width:34px; height:20px; border: 1px solid #c3c3c3;}
        .legend-label {display: table-cell; width:80px; height:23.5px; vertical-align: top; padding-left: 10px;}
        #explorer {position: fixed; z-index: 1; top: 60px; left: 15px;}
        table {border-collapse: separate!important;}
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

      <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a href="#" class="navbar-brand">EEMS3D - Prototype</a>
              </div>
              <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                      <li><a href="{% url 'dataset_upload' %}" target="_blank">Upload File</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                      <li><a href="#">Welcome, Guest</a></li>
                  </ul>
              </div>
          </div>
      </nav>
    <script src="{% static "js/dat.gui.min.js" %}"></script>
     <script src="{% static "js/three.min.js" %}"></script>
     <script src="{% static "js/OrbitControls.js"%}"></script>
    <div id="explorer" class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"></h3>
        <button type="button" class="panel-title" data-toggle="collapse" data-target="#eems-container" aria-hidden="false">EEMS Explorer</button>
      </div>
      <div id="eems-container" class="panel-body collapse">
        <div id="eems-zoomable">
          <div id="eems-tree"></div>
        </div>
      </div>
    </div>
    <div id="legend" class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">No variable selected</h3>
        </div>
        <div class="panel-body"></div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <div id="scene"></div>
      <script src="{% static "js/bootstrap-waitingfor.min.js" %}"></script>
    <script src="{% static "js/EEMS3D.js" %}"></script>
  </body>
</html>

templates/index_old.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EEMS 3D - Prototype</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <style>
        body { margin: 0; z-index: 1; }
        #scene { position:fixed; padding:0; margin:0; top:0; left:0; width: 100%; height: 100%; z-index: 0; }
        canvas {height: 100%; width: 100%;}
        #legend {position: fixed; top: 60px; right: 15px; z-index: 1}
        .legend-element {display: table-row; padding-left:10px;}
        .legend-image {display: table-cell;  width:34px; height:20px; border: 1px solid #c3c3c3;}
        .legend-label {display: table-cell; width:80px; height:23.5px; vertical-align: top; padding-left: 10px;}
        #explorer {position: fixed; z-index: 1; top: 60px; left: 15px;}
        table {border-collapse: separate!important;}
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

      <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a href="{% url 'explore' %}" class="navbar-brand">EEMS3D - Prototype</a>
              </div>
              <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                      <li><a href="{% url 'dataset_upload' %}" target="_blank">Upload File</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                      <li><a href="#">Welcome, Guest</a></li>
                  </ul>
              </div>
          </div>
      </nav>

     <script src="{% static "js/three.min.js" %}"></script>
     <script src="{% static "js/OrbitControls.js"%}"></script>
    <div id="explorer" class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"></h3>
        <button type="button" class="panel-title" data-toggle="collapse" data-target="#eems-container" aria-hidden="false">EEMS Explorer</button>
      </div>
      <div id="eems-container" class="panel-body collapse">
        <div id="eems-zoomable">
          <div id="eems-tree"></div>
        </div>
      </div>
    </div>
    <div id="legend" class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">No variable selected</h3>
        </div>
        <div class="panel-body"></div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <div id="scene"></div>
    <script src="{% static "js/deprecated/explore3d-alpha-deprecated.js" %}"></script>
  </body>
</html>

templates/modals/focalviews_about.html
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">About</h4>
      </div>
      <div class="modal-body">
          <p>Click on sites to view the sagebrush focal site data associated with it.</p>
          <p>Consensus and confidence are shown in the bottom left window along with raw values taken from available datasets at that location.</p>
          <p>Click and drag with the left mouse button to move the map, and hold the right mouse button to rotate the scene.</p>
          <p>Additional controls are available under the Terrain Controls menu in the bottom right.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload NetCDF4 File</title>
</head>
<body>
        <div class="container">
        <form enctype="multipart/form-data" class="form-signin" method="post">
            {% block title %}
            {% endblock title %}
            {% csrf_token %}
            <fieldset>
                {% comment %}
                {% for field in form %}
                    <div class="control-group">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">
                            {{ field }}
                            {% if field.errors %}
                                <span class="help-inline">
                                    {% for error in  field.errors %}{{ error }}{% endfor %}
                                </span>
                            {% endif %}
                            {% if field.help_text %}
                                <p class="help-inline"><small>{{ field.help_text }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                {% endcomment %}
                <div class="control-group">
                        <label class="control-label">Name</label>
                        <div class="controls">
                            <input id="id_name" maxlength="140" name="name" type="text">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Data file</label>
                        <div class="controls">
                            <input id="id_data_file" name="data_file" type="file">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Eems program</label>
                        <div class="controls">
                            <input id="id_eems_program" name="eems_program" type="file">
                                <p class="help-inline"><small>The EEMS program for the data</small></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Elev file</label>
                        <div class="controls">
                            <input id="id_elev_file" name="elev_file" type="file">
                                <p class="help-inline"><small>The file that contains the "elevation" </small></p>
                        </div>
                    </div>
            </fieldset>
            <div class="form-actions">
                <button id="submit-btn" type="submit" class="btn btn-primary btn-block" >Submit</button>
            </div>
        </form>
    </div>
</body>
</html>